concordiabook/urls.py
from django.contrib import admin
from django.urls import path
from textbooks import views

urlpatterns = [
    path('admin/', admin.site.urls),
   path('textbooks/<str:course_code>/', views.textbook_list, name='textbook-list'),
]

textbooks/models.py
from django.db import models

# Create your models here.
class Textbook(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    edition = models.CharField(max_length=100, null=True, blank=True)
    condition_choices= [
        ('new', 'New'),
        ('written', 'Written'),
        ('old','Old')
    ]
    condition = models.CharField(max_length=20, choices=condition_choices)
    course_code = models.CharField(max_length=10)
    availability = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title} ({self.course_code})"

textbooks/views.py
from django.shortcuts import render
from .models import Textbook

# Create your views here.
def textbook_list(request, course_code):
    textbooks = Textbook.objects.filter(course_code=course_code, availability=True)
    return render(request, 'textbook_list.html', {'textbooks': textbooks, 'course_code': course_code})

textbooks/templates/textbook_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ConcordiaBook</title>
    <link rel="stylesheet" href="{% static 'textbook_list_style.css' %}">

</head>
<body>
{% block content %}
<h2>Available Textbooks for {{ course_code }}</h2>
{% if textbooks %}
<ul>
    {% for book in textbooks %}
        <li>
            <strong>{{ book.title }}</strong><br>
            <ul class="details">
                <li> Author: {{ book.author }}</li>
                {% if book.edition %}<li> Edition: {{ book.edition }}</li>{% endif %}
                <li> Condition: {{ book.get_condition_display }}</li>
                <li> Course Code: {{ book.course_code }}</li>
            </ul>
        </li>
        {% endfor %}
</ul>
{% else %}
<p>No textbooks are currently available for this course.</p>
{% endif %}
{% endblock %}

</body>
</html>